name: Build Upstream
run-name: Running ${{ github.workflow }} by ${{ github.actor }}
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by ${{ github.event_name }} event"
      - run: echo "Building from branch ${{ github.ref }}"
      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y make build-essential python3 \
            python3-pyelftools yamllint gcc-aarch64-linux-gnu gcc-arm-none-eabi
      - name: Cache git repos
        uses: actions/cache@v4
        with:
          path: .git
          key: git-folder
          save-always: true
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Sync git submodules
        run: make gitsync
      - name: Build all configs
        run: BASE_FOLDER=${{ github.workspace }} ./MAKEALL
      - name: Save build summary
        uses: actions/upload-artifact@v4
        with:
          name: Build_results
          path: build-summary.txt
      - name: Save build errors
        uses: actions/upload-artifact@v4
        with:
          name: Error_results
          path: error-summary.txt
      - name: Deploy am64x_evm_hs_fs firmware
        uses: actions/upload-artifact@v4
        with:
          name: am64x_evm_hs_fs
          path: deploy/am64x_evm_hs_fs_all
      - name: Deploy am62x_evm_hsfs firmware
        uses: actions/upload-artifact@v4
        with:
          name: am62x_evm_hsfs
          path: deploy/am62x_evm_hsfs_all
      - name: Deploy am62x_beagleplay_gp firmware
        uses: actions/upload-artifact@v4
        with:
          name: am62x_beagleplay_gp
          path: deploy/am62x_beagleplay_gp_all
      - name: Deploy am62ax_evm_hs_fs firmware
        uses: actions/upload-artifact@v4
        with:
          name: am62ax_evm_hs_fs
          path: deploy/am62ax_evm_hs_fs_all
      - name: Deploy am62px_evm_hsfs firmware
        uses: actions/upload-artifact@v4
        with:
          name: am62px_evm_hsfs
          path: deploy/am62px_evm_hsfs_all
      - name: Deploy j721e_evm_gp firmware
        uses: actions/upload-artifact@v4
        with:
          name: j721e_evm_gp
          path: deploy/j721e_evm_gp_all
      - name: Deploy j721e_beagleboneai64_gp firmware
        uses: actions/upload-artifact@v4
        with:
          name: j721e_beagleboneai64_gp
          path: deploy/j721e_beagleboneai64_gp_all
      - name: Deploy j7200_evm_hs firmware
        uses: actions/upload-artifact@v4
        with:
          name: j7200_evm_hs
          path: deploy/j7200_evm_hs_all
      - name: Deploy j721s2_evm_hs_fs firmware
        uses: actions/upload-artifact@v4
        with:
          name: j721s2_evm_hs_fs
          path: deploy/j721s2_evm_hs_fs_all
      - run: echo "This job's status is ${{ job.status }}."
